import pygame
from Robot import *
# from DelieveryBot import *

class Environment:
    def __init__(self, dims: tuple, name: str, goal: pygame.rect):
        self.height = dims[0]
        self.width = dims[1]
        
        pygame.display.set_caption(name)
        self.map = pygame.display.set_mode((self.width, self.height))
        self.obstacles = []
        self.goal_box = goal
        self.goal_coord = goal.center

        self.m2p = 10  # 1 meter is 10 pixels
        
    def placeAreasOfInterest(self):
        """Displays the goal box and any obstacles
        """
        self.placeGoal()
        self.placeObstacles()
    
    def placeGoal(self):
        """Places the goal set in initialization
        """
        pygame.draw.rect(self.map, (100, 255, 100), self.goal_box)
    
    def createObstacle(self, origin:tuple, size:tuple):
        """Places an obstacle in the environment

        Args:
            origin (tuple): Top left corner of the obstacle
            size (tuple): Width and height of the obstacle
        """
        obstacle = pygame.Rect(origin, size)
        self.obstacles.append(obstacle)
    
    def placeObstacles(self):
        """Places all the obstacles in the environment
        """
        for obstacle in self.obstacles:
            pygame.draw.rect(self.map, (255, 0, 0), obstacle)
    
    def checkCollision(self, rectangle: pygame.Rect):
        """Checks if an inputted rectangle (like a robot hitbox) collides with an obstacle

        Args:
            rectangle (pygame.Rect): Rectangle to check if it is colliding with an obstacle.

        Returns:
            bool: True if it is colliding with an obstacle. False otherwise.
        """
        return rectangle.collidelist(self.obstacles) != -1
    
    def drawTrailerPath(self, path):
        """Plots the truck and trailer path in the environment

        Args:
            path (list): List of trailerbot states to plot
        """
        if len(path) == 0:
            return None
        last = path.pop()
        while len(path) != 0:
            next = path.pop()
            pygame.draw.line(self.map, (255, 0, 255), (int(last.car_x), int(last.car_y)), (int(next.car_x), int(next.car_y)), width=2)
            pygame.draw.line(self.map, (255, 255, 0), (int(last.trailer_x), int(last.trailer_y)), (int(next.trailer_x), int(next.trailer_y)), width=2)
            last = next

    def drawPath(self, path):
        """Plots the path generated by the kinematic planner

        Args:
            path (list): List of robot states to plot
        """
        if len(path) == 0:
            return None
        last = path.pop()
        while len(path) != 0:
            next = path.pop()
            pygame.draw.line(self.map, (0, 0, 0), (int(last.x), int(last.y)), (int(next.x), int(next.y)), width=2)
            last = next
    
    def highlightPixel(self, pixel: tuple):
        """Highlights the desired pixel in the environment

        Args:
            pixel (tuple): The pixel to be highlighted
        """
        self.map.set_at((pixel), (0, 0, 255))
                
    
    
        
